# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 3
# Label requiring a response
responseRequiredLabel: attente-retour-utilisateur
# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  Cette *issue* a été automatiquement fermée car il n'y a eu aucune réponse complémentaire
  de la part de l'auteur. N'hésite pas à reposter ici si tu as d'autres questions.
